use_frameworks!

platform :ios, '9.0'

target 'LGLExtension_Example' do
  pod 'LGLExtension', :path => '../'

  target 'LGLExtension_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
